name: boremi_env
channels:
  - conda-forge
dependencies:
  - python==3.11.5
  - jupyterlab==3.6.3
  - pip==23.1.2
  - git
  - nodejs
  - pip:
    - ipykernel==6.25.0
    - bokeh>=3.5.0 # until release of bokeh 3.6.0 with fix for https://github.com/bokeh/bokeh/issues/13987 , instead use the development version below for clusters
#    - -e git+https://github.com/bokeh/bokeh.git@18ee70bb5d5a4996143a7d50f32fbd9ae341c4ea#egg=bokeh
    - jupyter_bokeh>=3.0.2
    - anndata>=0.8.0
    - pandas==1.3.5
    - numpy>=1.21.0,<1.24.0
    - Pillow>=9.2.0
    - matplotlib>=3.6.0
    - nbformat>=5.3.0
    - jupyter-server-proxy
    - ipywidgets==8.0.4
    - ipython==8.26.0
